### ISSUE TITLE
Amazon S3: Cannot save/write database file to root of bucket

### ISSUE THREAD

**Issue by mxscho** [Kyrodan/KeeAnywhere#58] opened 2016-10-05 18:06 UTC
When using Amazon S3 buckets as the storage location for a KeePass database file, it is possible for me to open/read database files from it, but not save/write them.
When I try to save a KeePass database file to an Amazon S3 url using this plugin after having it opened successfully from the same url, I always get this error:

> s3:///[my-s3-account]/[my-s3-bucket]/database
> Failed to save the current database to the specified location!
> One or more errors occurred.
> The target file might be corrupted. Please try saving again. If that fails, save the database to a different location.

`my-s3-account` should default to `"S3 Account"` when just creating a single S3 storage location as far as I know.

For testing purposes, I attached the `AmazonS3FullAccess` policy to the AWS user account which is used by this plugin (from which the access/secret keys are taken). This should enable full access to all S3 buckets, which is way more than the plugin should require.
The KeeAnywhere settings dialog also confirms me access to the account/S3 bucket when checking.

I'm not quite sure if there might even be a problem with the path I am using. My file is indeed just called `"database"` without any file extension and placed in the root directory/the corresponding bucket itself.
However, I remember that I actually tried saving it to another file name and that has failed as well.

Due to a lack of other accounts I haven't been able to test any other supported provider yet.
I'm not using any other storage-based plugins with KeePass, just KeeAgent and KeePassHttp which should not do something related to the features of this plugin.

**Comment by Kyrodan** [comment] 2016-10-06 07:02
Hi @mxscho,

I can reproduce this: You cannot save to the root of your bucket (even if you have loaded from there).
This seems to be a bug I will fix for next release.

Workaround: load and save in a folder within your bucket.

Regards,
Daniel

**Comment by mxscho** [comment] 2016-10-06 13:20
I can confirm that this works perfectly. Thanks for that!

**Comment by richardcmckinney** [comment] 2017-03-08 04:11
@Kyrodan was this bug fixed in the most recent release? 
thanks for your work on KeeAnywhere.

**Comment by Kyrodan** [comment] 2017-03-08 07:45
No, in recent version 1.3.1 this is still open. It's fixed in code for the upcoming 1.4.0 release.

**Closed** 2017-05-31 08:01 UTC
Labels: bug
