### ISSUE TITLE
Keepass 2.40 vs KeeAnywhere 1.4

### ISSUE THREAD

**Issue by cgabba** [Kyrodan/KeeAnywhere#143] opened 2018-09-18 09:49 UTC
Hi I'm ssing Keepass 2.40 and KeeAnywhere 1.4 on Windows 10.0.16299.665, after keepass upgrade keeanywhere hang with this error.
Could you please help?
thank you
![2018-09-18 11_39_43-keepass](https://user-images.githubusercontent.com/43372351/45679422-ec310b80-bb38-11e8-9018-c8bef92bbdbf.jpg)

**Comment by Kyrodan** [comment] 2018-09-18 09:54
Duplicate of #141. 
Please see temporary solution here: https://github.com/Kyrodan/KeeAnywhere/issues/141#issuecomment-420277828

**Closed by Kyrodan** 2018-09-18 09:54 UTC
Labels: duplicate
