### ISSUE TITLE
Unable to Access OneDrive Account

### ISSUE THREAD

**Issue by shad0whawk** [Kyrodan/KeeAnywhere#159] opened 2018-12-16 00:25 UTC
I downloaded your plugin with hopes of using it to sync my database with my OneDrive for Business account.  I've tried adding my account after select OneDrive but the next page doesn't accept my email address and tells me to enter a valid Microsoft email.  Other applications will use my email address and redirect me to my organizations web page to login.  Is this a limitation of your plugin that doesn't allow connection to OneDrive with an email address that doesn't end in *outlook.com, live.com, etc.?

**Comment by Kyrodan** [comment] 2019-02-07 15:56
Duplicate of #28. Please follow discussion there.

**Closed by Kyrodan** 2019-02-07 15:56 UTC
Labels: duplicate
