### ISSUE TITLE
Plugin is incompatible with current KeePass version

### ISSUE THREAD

**Issue by msroth** [Kyrodan/KeeAnywhere#129] opened 2018-04-06 02:22 UTC
This error suddenly appeared this evening.  I am using KeePass v2.38 and KeeAnywhere 1.4.1 on Windows 7.  I am using the same version of KeePass and KeeAnywhere on a Windows 10 computer with no issues.  There have been no updates to the Windows 7 computer other than I changed my domain password.
![image](https://user-images.githubusercontent.com/4048670/38400769-cd653f32-391f-11e8-962c-e284b8ce7559.png)

**Comment by Kyrodan** [comment] 2018-04-06 06:36
Duplicate of #95

**Closed by Kyrodan** 2018-04-06 06:36 UTC
Labels: duplicate
