### ISSUE TITLE
Cannot open KeePass file from GoogleDrive if it's in shared directory

### ISSUE THREAD

**Issue by bfejervari** [Kyrodan/KeeAnywhere#337] opened 2022-05-03 19:54 UTC
I used to use a KeePass file shared with another Google user, as follows:
- the file is hosted in another user's GoogleDrive
- the another user's GoogleDrive is shared with me (full access)
- I created a "link" in my GoogleDrive to that shared folder
- I opened the file as being local (made a Windows shortcut and calling `KeePass.exe "gdrive:///MyUserName/shared_and_linked_folder/keepass.kdbx" -ioiscomplete` command)

Locally (in my own GoogleDrive) stored KeePass files can be opened.

**The problem**:
About a week (or some time) ago I found out that cannot open the KeePass file any more. Recreated the link in the own GoogleDrive didn't help.
In KeeAnywhere file browser, the linked (shared) folder doesn't show up, so the file cannot be selected from the gui.

Any solution or workaround would be appreciated.

**Comment by Jackabomb** [comment] 2022-09-06 21:03
Duplicate of #223. As for why it used to work, see tvanderelsen's [comment on this also-identical issue.](https://github.com/Kyrodan/KeeAnywhere/issues/339#issuecomment-1236819934)

**Closed** 2024-06-17 07:41 UTC
