### ISSUE TITLE
Dropbox Account Creation - Outdated Browser

### ISSUE THREAD

**Issue by mtmaiman** [Kyrodan/KeeAnywhere#254] opened 2021-02-18 21:38 UTC
When I attempt to add a Dropbox account in the settings, I select "Dropbox" from the drop down and receive this dialogue box:

![image](https://user-images.githubusercontent.com/53130507/108424835-4bf6d980-71ff-11eb-943f-a116438452da.png)

Not sure how to get around this.

**Comment by Kyrodan** [comment] 2021-02-19 06:41
Duplicate of #237.
A Beta-Build can be testet from #252.

**Closed by Kyrodan** 2021-02-19 06:41 UTC
