### ISSUE TITLE
Illegal Characters in path

### ISSUE THREAD

**Issue by cdurth** [Kyrodan/KeeAnywhere#38] opened 2016-06-09 17:20 UTC
When trying to load from google drive, i get the following error.

![image](https://cloud.githubusercontent.com/assets/3444087/15939241/d4d96258-2e44-11e6-8a35-ad331d4f8a34.png)

**Comment by cdurth** [comment] 2016-06-09 17:21
And i have found the cause error. It does not like < or > in file names

**Comment by Kyrodan** [comment] 2016-06-09 18:06
Duplicate of #23. It is already fixed in current development beanch. Hope I
get the next version out very soon.

Corey Durthaler <notifications@github.com> schrieb am Do., 9. Juni 2016,
19:21:

**Comment by Kyrodan** [comment] 2016-06-15 12:02
New release is out, please test it.

**Closed** 2016-06-15 12:16 UTC
Labels: duplicate
