### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by iliyesku** [Kyrodan/KeeAnywhere#146] opened 2018-09-28 12:30 UTC
I tried to run this wonderful plugin on Linux, but it was failed with error referring on ".Net Framework 4.5.2 or newer" prerequisite.

Can you add .net core support to make it possible to run on Linux?

**Comment by Kyrodan** [comment] 2018-10-19 08:03
Duplicate of #18

**Closed by Kyrodan** 2018-10-19 08:03 UTC
Labels: duplicate
