### ISSUE TITLE
Problem with Google Drive

### ISSUE THREAD

**Issue by amidvo** [Kyrodan/KeeAnywhere#176] opened 2019-05-17 21:18 UTC
Hello.

Keepass 2.41 (or 2.39-1) + KeeAnywhere1.51 not working properly with Google Drive through Fortigate Proxy.

An error: 
```
Authentication failed!

An error occurred while sending the request.
Google.Apis.Core
   в Google.Apis.Http.ConfigurableMessageHandler.<SendAsync>d__59.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.<ExecuteAsync>d__0.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<FetchTokenAsync>d__35.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<ExchangeCodeForTokenAsync>d__30.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в KeeAnywhere.StorageProviders.GoogleDrive.GoogleDriveStorageConfigurator.<Claim>d__c.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в KeeAnywhere.OAuth2.OAuth2Form.<OnNavigated>d__3.MoveNext()
Void MoveNext()


Inner:
Удаленный сервер возвратил ошибку: (407) Требуется аутентификация посредника.
System
   в System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   в System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
System.IO.Stream EndGetRequestStream(System.IAsyncResult, System.Net.TransportContext ByRef)
```
My translate: `the remote server returned an error: (407) proxy authentication required.`

But combination Keepass 2.39-1 and KeeAnywhere 1.41 working properly.

**Comment by Kyrodan** [comment] 2019-11-29 13:33
Maybe duplicate of #123 
Therefore closing this. Please reopen, if v1.6.0 does not solve your issue.

**Closed by Kyrodan** 2019-11-29 13:33 UTC
Labels: duplicate

**Comment by impulse200** [comment] 2020-03-12 11:02
Hello.

I ran into similar issue with "Proxy Authentication Required". But the root of it in fact that KeeAnywhere does not honor KeePass proxy settings but using system setting. 

I have KeePass proxy set to one that does not require authentication. But when trying to log into Google Drive account I do not see any requests from the PC on that proxy.
