### ISSUE TITLE
Why "Saving provider credentials in a KeePass database" is in blacklisted features?

### ISSUE THREAD

**Issue by milten89** [Kyrodan/KeeAnywhere#170] opened 2019-03-27 09:12 UTC
Hi,

I can't find any information why this feature is blacklisted. There are KeePass restriction on this or some other issues?

For example if I want to add account to KeeAnywhere, first I need to copy user name and password somewhere as plain text and then past it to authentication window. I can't copy it directly from KeePass, because KeeAnywhere settings and authentication windows are dialog.

Copying user name is small issue, because probably this is email address so You already remember it, but password is a huge issue, because for some time it is accessible for anyone.

Best regards

**Comment by JigAma** [comment] 2019-03-28 22:24
There is another plugin called [https://sourceforge.net/projects/kp-googlesync/](GoogleSyncPlugin) which just let you pick the Gmail entry in your Database and then use it to connect on your GDrive account.

The problem is each time i launch  Keepass, Keepass freeze because something doesn't work well in the plugin it seems.

I wish KeeAnywhere would use the same system for login credentials. Wouldn't it be even more secure because the credentialss are not stored outside Keepass by the way ?

**Comment by Kyrodan** [comment] 2019-11-19 19:35
You can dtore the Provider Password itself in Tour database. I will check, whether I can improve the authentication Dialog to Support Copy-paste *out* of the database to the authentication window. What is blacklistet: open a local database in which the *tokens* are stored to open another cloud stored database - like in KeeCloud. In my opinion this is too complicated for most users.

**Comment by Kyrodan** [comment] 2019-11-29 12:57
In #155 the Dialog problem will be fixed.
Closing this, because I think the question is answered here.

**Closed by Kyrodan** 2019-11-29 12:57 UTC
Labels: question

**Comment by gab** [comment] 2021-04-30 16:54
> You can dtore the Provider Password itself in Tour database. I will check, whether I can improve the authentication Dialog to Support Copy-paste _out_ of the database to the authentication window. What is blacklistet: open a local database in which the _tokens_ are stored to open another cloud stored database - like in KeeCloud. In my opinion this is too complicated for most users.

The scenario which I'm using with KeeCloud is that I open my database and sync it with its Dropbox copy using the URL I have in `File -> Synchronize -> Recent Files`. It's a lot more secure than to store the credentials outside the database, and I'd argue it's not complicated - although the KeeCloud UI does make it complicated to set up.

For use at work where IT can access all your files, having the tokens be encrypted inside your database is really a desirable feature - especially if you're using Google Drive where you have to grant access to all your files, not only a subfolder.
