### ISSUE TITLE
KeeAnywhere...plgx fails on Linux with .NET version complaint

### ISSUE THREAD

**Issue by jamesdavidhoward** [Kyrodan/KeeAnywhere#111] opened 2017-10-02 06:36 UTC
Upon installing KeeAnywhere-1.4.1.plgx (by copying it into a freshly-created .../plugins directory). KeePass attempts to run the plugin, but it fails with a message:
> /usr/lib/keepass/plugins/KeeAnywhere-1.4.1.plgx
The plugin cannot be loaded.
A newer .NET framework is required.

This is running on Fedora 26 for x86-64, with Mono ver. 4.8.0-7.fc26.  _Note_ that KeePass, invoked within mono otherwise runs fine.

I'm unaware what version of .NET this version of Mono implements, and the message does not tell anything about the version of .NET that the plugin is requesting.

Suggestions?

**Comment by hackel** [comment] 2017-10-12 03:15
My suggestion is to learn to read.  Seriously, did you even look at #18?  Please close this and next time search first!

**Closed** 2017-10-23 06:56 UTC
Labels: duplicate

**Comment by MichaelCain2** [comment] 2020-07-08 16:58
> My suggestion is to learn to read. Seriously, did you even look at #18? Please close this and next time search first!

I read it, like they did,  you amazing tool. Tell me where in there #18 it addresses a fix to the issue. Because I am sure now three years after this amazing post, the issue is still an issue. So, any other input notreally-hackel, you might have or can we expect more tiny cockery to be expewed from your vast depth of non-wisdom?

**Comment by Kyrodan** [comment] 2020-07-13 13:29
KeeAnywhere is not compatible with Mono/Linux.

There are some community approaches to make things partly working. Use #18
to discuss that, that's okay for me.
But: I don't think I will ever find the time and have the resources to
support Linux/Mono. It is a spare time project and it's very hard for me to
fix known bugs or to implement necessary new functions (like abandon
internal browser for authorization).
Sorry for your inconveniences.

Regards,
Daniel

Am Mi., 8. Juli 2020 um 18:58 Uhr schrieb Stryker Cain <
notifications@github.com>:

**Comment by gulhe** [comment] 2022-02-03 15:17
It's with deep sorrow that I read this.
Nevertheless, thank you for all, the time, effort and brainjuice you put in this project.
My daily life is easier thanks to you. (wanted to let you know)
