### ISSUE TITLE
Long Refresh Tokens lead to: The following plugin is incompatible with the current Keepass version

### ISSUE THREAD

**Issue by LegoChicken** [Kyrodan/KeeAnywhere#95] opened 2017-07-19 10:38 UTC
Using Keepass 2.36 and KeeAnywhere 1.4.1 on two machines. One machine works fine, the other generated the following error. Both machines running Windows 7 Professional Service Pack 1
![image](https://user-images.githubusercontent.com/2156602/28362986-8b4be9b4-6c76-11e7-9ae4-9cc74eeb36ac.png)

**Comment by Kyrodan** [comment] 2017-08-07 12:33
Did you copied your KeeAnywhere.Accounts.json from one machine to another?
If yes: this won't work. Your account file is encrypted with a machine specific key which cannot be decrypten on another machine.

Maybe I should implement a better problem handling for this case.

**Comment by LegoChicken** [comment] 2017-08-07 13:10
No, I didn't move it between machines. It just stopped working one day. I don't know if was after update to KeePass or KeeAnywhere. I intend to uninstall KeePass & plugins and reinstall.

**Comment by Kyrodan** [comment] 2017-08-07 13:20
Hmm, seems it has to do with this:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/4e3ada0a-bcaf-4c67-bdef-a6b15f5bfdce/key-not-valid-for-use-in-specified-statewhat-do-you-mean?forum=clr

**Comment by amuagarwal** [comment] 2017-08-09 17:24
I am not getting any error but there is no menu item in FIle Open. And even no errors  Any help

**Comment by AlexEshoo** [comment] 2017-10-26 20:30
I am also experiencing this issue. I also did not move the json file around. I am on keepass 2.37, i tried downgrading to 2.35 as well but no luck. Hope this gets fixed.

**Comment by laurentlbm** [comment] 2018-01-25 14:41
On my end, the problem is probably related to the fact that my work computer changed name and AD domain. I deleted all the KeePass user files (`C:\Users\...\AppData\Local\KeePass`) and it started working again.

**Comment by msroth** [comment] 2018-04-06 11:46
Deleting C:\Users\...\AppData\Local\KeePass cleared up the problem for me.

**Comment by Kyrodan** [comment] 2019-11-29 12:59
Problem will be improved with #169 
Therefore closing this. Please reopen if it still exists in next v1.6.0 of the plugin.

**Closed by Kyrodan** 2019-11-29 12:59 UTC
Labels: bug
