### ISSUE TITLE
Not able to connect to a AWS S3 bucket with a IAM policy

### ISSUE THREAD

**Issue by adrienbuffet** [Kyrodan/KeeAnywhere#187] opened 2019-10-23 14:37 UTC
Hello.

I'm trying to connect to a AWS S3 bucket without giving the S3FullAccess policy.
It's still not working...
I've been so far to : 
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::mybucketname"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "s3:*Object",
            "Resource": [
                "arn:aws:s3:::mybucketname/*"
            ]
        }
    ]
}`

Can you help ?

Thanks.

**Comment by Kyrodan** [comment] 2019-11-22 10:54
Duplicate of #116?

**Comment by adrienbuffet** [comment] 2020-01-06 10:11
Hello. I was able to connect to the bucket using this custom policy : 
``
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucketVersions",
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::my-bucket-name"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:GetObjectVersionTagging",
                "s3:DeleteObject",
                "s3:GetObjectVersion"
            ],
            "Resource": "arn:aws:s3:::my-bucket-name/*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        }
    ]
}``

**Comment by Kyrodan** [comment] 2020-01-08 07:34
Wow, thanks for reporting your success. I would like to add this info to the documentation.

**Comment by adrienbuffet** [comment] 2020-01-08 09:45
This IAM policy doesn't restrict the listing of the directories in the 

> Duplicate of #116?

It's not.

> The Amazon subscription where my user is connecting has an Identity Provider configured in order to allow all users to use SAML authentication method.

I'm not using any identity provider. Just regular IAM users

**Comment by adrienbuffet** [comment] 2020-01-08 09:50
> Wow, thanks for reporting your success. I would like to add this info to the documentation.
My pleasure :)

**Comment by Kyrodan** [comment] 2020-01-08 09:50
Ok, thanks for you latest feedback. So this Ticket is solved for you?

**Comment by adrienbuffet** [comment] 2020-01-08 09:56
Yes it is.

In order to permit a specific IAM user to write in multiple keepass databases (stored in their own buckets), the simplest way is to add multiple IAM Policies to a user, changing the bucket name every time in the policy.

Then, the user can browse multiple keepass and see those buckets as "folders" in the interface.

**Comment by adrienbuffet** [comment] 2020-01-08 09:56
![Sans titre](https://user-images.githubusercontent.com/10338113/71968608-91c42e80-3205-11ea-977c-080de7d7bf57.png)

**Comment by adrienbuffet** [comment] 2020-01-08 09:58
If a person hasn't the right IAM Policy attached to the IAM user he is connected to, 
he will get an error like this :

![Sans titre](https://user-images.githubusercontent.com/10338113/71968749-ccc66200-3205-11ea-95ca-528382f1a088.png)

**Comment by Kyrodan** [comment] 2020-01-09 07:53
I added documentation to the FAQ-Section of the Homepage:
https://keeanywhere.de/use/faq

**Closed by Kyrodan** 2020-01-09 07:53 UTC
Labels: documentation

**Comment by mwhouser** [comment] 2020-07-01 15:49
@Kyrodan I have created a CloudFormation template here: https://github.com/mwhouser/keepass-storage-cfn-templates

This template will create an S3 bucket, IAM user, and setup the permissions. Feel free to examine and critique.
