### ISSUE TITLE
Not able to configure AWS S3 with AWS MFA enabled user.

### ISSUE THREAD

**Issue by htshekhada** [Kyrodan/KeeAnywhere#186] opened 2019-10-17 06:32 UTC
I am trying to add Amazon S3 with my AWS access key and secret key, my user is MFA enabled but there is no way I can give virtual token along with access key and secret key!

**Comment by Kyrodan** [comment] 2019-11-20 19:06
Maybe duplicate of #116?

**Comment by Kyrodan** [comment] 2020-01-09 07:58
Just released version 1.6.0 which hopefully implements this feature.
Please try this.

**Closed by Kyrodan** 2020-01-09 07:58 UTC
Labels: duplicate
