### ISSUE TITLE
Version incompatibility KeeAnywhere 1.3.1 and KP 2.35

### ISSUE THREAD

**Issue by tschroeder13** [Kyrodan/KeeAnywhere#79] opened 2017-05-08 10:11 UTC
Hey,
I installed this plugin (v1.3.1) and restarted KP. Following error message occurs:
![image](https://cloud.githubusercontent.com/assets/822698/25799863/174463ce-33e7-11e7-8c62-9d26a2e6f054.png)
KP is verison 2.35
![image](https://cloud.githubusercontent.com/assets/822698/25799885/2caa201e-33e7-11e7-817f-31e7af4b50ce.png)
.NET FW is in version 4.6.2
![image](https://cloud.githubusercontent.com/assets/822698/25799982/a4e71aa0-33e7-11e7-8b31-a36418d628c1.png)

Thx in advance and kind regards
Tobias

**Comment by Kyrodan** [comment] 2017-05-08 10:20
Hi @tschroeder13 ,

there is no known compatiblity issue with KeePass 2.35, so KeeAnywhere 1.3.1 should work in general (and does by many others).

What you can do:
* Do you tried it on an "installed" version of KeePass, too? 
* You also could try a developer-snapshot of the upcoming 1.4.0 (https://github.com/Kyrodan/KeeAnywhere/files/929813/KeeAnywhere-1.4.0-unstable.plgx.zip)

Regards,
Daniel

**Comment by tockar** [comment] 2017-05-09 15:38
Same issue for me. It worked perfectly for my just yesterday. Today I've installed Windows on my new PC and it doesn't work, and 1.4.0 isn't working either. Same error.

**Comment by Kyrodan** [comment] 2017-05-19 07:26
Hmm, I can't reproduce this issue :-(
Maybe .Net 4.6.2 is the problem, I only have 4.6.1 installed. I will take a look into this direction.

**Comment by Kyrodan** [comment] 2017-05-19 07:27
@tschroeder13: does a hive for .Net 4.6.1 exists in your registry?

**Comment by tockar** [comment] 2017-05-19 07:54
Use fresh Windows install and try using existing Keepass configuration on new Windows installation. So, copy both Keepass directories from AppData\Local and AppData\Roaming. Launch KeePass, then error will show up. 

The "fix" for this is to reset your KeePass config by deleting these folders and start from the beginning, but as you probably know it is kinda annoying. KeePassHttp, for example, does not have this issue and works fine when you move your config.

**Comment by Kyrodan** [comment] 2017-05-19 08:03
Hi @tockar, 
thanks for sharing your experience and your "fix". Maybe it has to do with plugin caching of KeePass itself. Deleting only contents of AppData\Local\KeePass\PluginCache could perhaps solve this issue.

So I'm closing this issue.

**Closed by Kyrodan** 2017-05-19 08:03 UTC

**Comment by tockar** [comment] 2017-05-19 11:58
No, deleting contents of PluginCache\ does not solve the issue.
