### ISSUE TITLE
Automatic Backup not triggering

### ISSUE THREAD

**Issue by fuytters** [Kyrodan/KeeAnywhere#167] opened 2019-02-11 14:28 UTC
Hello, I'm using KeePass for quite some time now and recently started using the KeeAnywhere plugin. Installation with Google Drive went fine (on 31 Jan 2019) and a copy of the database is on Google Drive. Since then I made several changes to the database but both locally as well on Google Drive no additional backups have been made. Am I doing something wrong? A setting in KeePass I need to verify?

Thanks!

**Comment by Heeere-GittyGitty** [comment] 2019-03-28 20:35
Same here. Latest on Win10

**Comment by bfejervari** [comment] 2019-06-06 08:18
In advance: good work, nice plugin!

I wanted to make a Request, but maybe it's connected to this issue.
I use a database on GoogleDrive. It works well, KeeAnywhere synchronizes it both directions.
The Request I would make:
* while loading the database which was changed on the Cloud side,
* the fact of change should trigger the Backup Mechanism (just as 'Save' do).

Reproducing this case:
* create a databes and save on Cloud (I used gdrive:///...)
* I use Google Backup and Sync, so the saved database syncs to my local drive
* I open and edig it with "standalone" KeePass, put some new keys in it
* Google Backup and Sync puts it back to cloud
* while I open it again with KeeAnywhere, the new keys are visible
  * but after opening without network connection: opening the last backup, it doesn't show the changed version

Because of this, I assume that the noticed change should trigger local Backup mechanism.

Best regards,
Bence

**Comment by titou4307** [comment] 2019-11-20 11:00
Hello
I have the same problem but may be I'm not doing like it needeed :
I use a local database and I want to maka backup auto on google but the data base is not actualised each time I modify the data base on local on after modifications....

Any help
Thanks

**Comment by paymanz** [comment] 2022-01-28 10:59
it doesn't sync my database on Dropbox either! and connection is OK as i click on check button.

**Comment by Kyrodan** [comment] 2024-06-24 08:01
Maybe fixed in 2.1.0

**Closed by Kyrodan** 2024-06-24 08:01 UTC
