### ISSUE TITLE
KeeAnywhere incompatible

### ISSUE THREAD

**Issue by spymaxx** [Kyrodan/KeeAnywhere#150] opened 2018-10-06 18:56 UTC
tried installing the plugin and get this error:

![capture](https://user-images.githubusercontent.com/43915260/46574832-eaa87580-c977-11e8-9870-e39f888a2006.PNG)

**Comment by claudiuconstantin** [comment] 2018-10-18 13:08
Are you using the latest release of the plugin + latest version of Keepass?

**Comment by Kyrodan** [comment] 2018-10-19 08:06
Maybe duplicate of #147. Will add improved loading of Microsoft.Graph.Core-Library in version 1.5.1

Please reopen this issue, if you have a problem after upgrading to version 1.5.1 (which will be released later today).

**Closed by Kyrodan** 2018-10-19 08:06 UTC
Labels: duplicate
