### ISSUE TITLE
Illegal characters in path for Google Drive account

### ISSUE THREAD

**Issue by hach-que** [Kyrodan/KeeAnywhere#33] opened 2016-05-14 03:24 UTC
First time I open the open from Cloud Drive dialog after setting up my account I get this:

![image](https://cloud.githubusercontent.com/assets/504826/15265930/25a398e8-19d7-11e6-82b3-e20ea1b4f57d.png)

Changing the dialog for *.* All Files, I get this exception:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<OnFilterChanged>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.32.0.23563
    Win32 Version: 2.32.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Newtonsoft.Json.DLL
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/CredentialManagement.DLL
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.32.0.23563
    Win32 Version: 2.32.0.23563
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.10.0.1
    Win32 Version: 1.10.0.1
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.10.0.25332
    Win32 Version: 1.10.0.25332
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.10.0.25331
    Win32 Version: 1.10.0.25331
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.10.0.25333
    Win32 Version: 1.10.0.25333
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
Microsoft.Threading.Tasks
    Assembly Version: 1.0.12.0
    Win32 Version: 1.0.168.0
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Microsoft.Threading.Tasks.DLL
----------------------------------------
Google.Apis.Auth.PlatformServices
    Assembly Version: 1.10.0.25333
    Win32 Version: 1.10.0.25333
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Google.Apis.Auth.PlatformServices.DLL
----------------------------------------
Google.Apis.PlatformServices
    Assembly Version: 1.10.0.25332
    Win32 Version: 1.10.0.25332
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Google.Apis.PlatformServices.DLL
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Primitives/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Primitives.dll
----------------------------------------
Microsoft.Threading.Tasks.Extensions.Desktop
    Assembly Version: 1.0.168.0
    Win32 Version: 1.0.168.0
    CodeBase: file:///C:/Users/June/AppData/Local/KeePass/PluginCache/yMX32auyl02XGX0KgVL6/Microsoft.Threading.Tasks.Extensions.Desktop.DLL
----------------------------------------
System.Net
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1564.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

If it helps, this is a Google Apps for your Domain account.

**Comment by Kyrodan** [comment] 2016-05-15 19:09
Maybe it's a duplicate of #23. Could you please check, whether you have files in your root Google Drive folder with "unusual characters" like quotation marks, slashes or something like that?

**Closed** 2016-05-20 12:24 UTC
Labels: duplicate
