### ISSUE TITLE
v1.5.1 Incompatible with KeePass 2.43???

### ISSUE THREAD

**Issue by AIVAS001** [Kyrodan/KeeAnywhere#192] opened 2019-12-04 12:54 UTC
I could swear this was working fine with this version of KeePass for a while but I might be wrong.

![image](https://user-images.githubusercontent.com/38560599/70143988-ff12fb80-166a-11ea-87b9-3367eb838e8a.png)

Same error regardless if installed manually or with Chocolatey.
KeeAnywhere v1.5.1
KeePass v2.43 installed w/ Chocolatey.
Windows 10 (1909 build 18363.476)

**Comment by Kyrodan** [comment] 2019-12-04 13:19
This is not a compatibility issue. It's a problem of the decryption of your configuration-file-secrets.See details under "Could not read account configuration" of https://keeanywhere.de/use/troubleshooting.Your problem will be handled better in the upcoming 1.6.0-Release.

Duplicate of #150

**Closed by Kyrodan** 2019-12-04 13:19 UTC
