### ISSUE TITLE
KeeAnywhere-1.5.1 plugin incompatible with Keepass 2.41

### ISSUE THREAD

**Issue by Squale76** [Kyrodan/KeeAnywhere#175] opened 2019-05-15 08:58 UTC
After installing KeePass v2.42.1, the KeeAnywhere-1.5.1.plgx plugin has detected as incompatible
![image](https://user-images.githubusercontent.com/6738458/57762722-4d2cd580-7700-11e9-8baf-c4315748fcb9.png)

**Comment by Kyrodan** [comment] 2019-05-15 10:14
That's weird. I can't reproduce this issue: on my machine it works as
expected after the upgrade of KeePass

Am Mi., 15. Mai 2019 um 10:58 Uhr schrieb Squale76 <notifications@github.com

**Comment by HelOWeen** [comment] 2019-05-25 06:54
Same here, running on Windows 10 Prof. 1809 (German), 64 bit. .NET Framework 4.7.2

Here's the callstack:

[Expanded Information]
Schlüssel ist im angegebenen Status nicht gültig. *)

System.Security
   bei System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   bei KeeAnywhere.Json.ProtectedDataStringPropertyResolver.ProtectedDataStringValueProvider.SetValue(Object target, Object value)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei KeeAnywhere.Configuration.ConfigurationService.LoadAccountsFromLocalSecureStore()
   bei KeeAnywhere.Configuration.ConfigurationService.Load()
   bei KeeAnywhere.KeeAnywhereExt.Initialize(IPluginHost pluginHost)
   bei KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)
Byte[] Unprotect(Byte[], Byte[], System.Security.Cryptography.DataProtectionScope)

*) Translates to "Key is invalid in the current state."

**Comment by DesuZaKiddo** [comment] 2019-06-01 09:50
I have the same problem 
Appeared on the latest windows version (1903), worked on the previous version
![Keepass](https://user-images.githubusercontent.com/51260990/58746850-d582d880-846b-11e9-8ea8-ea238cd922a2.jpg)

**Comment by onuruslu** [comment] 2019-06-07 03:21
@Squale76 @Kyrodan @HelOWeen @DesuZaKiddo I had the same problem too. I realized that I didn't delete the old version's "xxx.plgx" file. When I remove it, the plugin worked correctly.

**Comment by Squale76** [comment] 2019-06-07 04:30
I deleted old version, download v1.5.1 and restart KeePass. After recompilation of plugin by KeePass v2.42.1 on windows 10.
![image](https://user-images.githubusercontent.com/6738458/59081284-8fa39580-88ed-11e9-85e2-62d21d5f9330.png)

**Comment by Kyrodan** [comment] 2019-06-07 06:35
Hi together,

there seem to be two/three different issues:
* after Upgrading KeePass the PLGX-Cache is not cleared and the plugin does
not get recompiled: please delete content of Plugin Cache Folder
* @Squale76 issue with "System.Drawing.Point": I don't know why this
happens. Which .Net-Framework on which Windows-Version do you use?
* @DesuZaKiddo issue with Cryptographic: The encrypted tkoens from
KeeAnxwhwre.Accounts.json could not be decrypted: this happens, if the
config-file is copied/used by a different user. Just reauthenticate and it
should work again.

Regards,
Daniel

Am Fr., 7. Juni 2019 um 06:30 Uhr schrieb Squale76 <notifications@github.com

**Comment by ka5huk3n** [comment] 2019-06-08 15:54
Yeah it resolved the issue. Had few things happened at once at the same time - reinstalled Win 10 to May update after boot related failure, updated Keepass and started receiving Crypto error each time at launch.
After deleting plugin cache in AppData AND removing KeeAnywhere.Accounts.json in Keepass folder, error was gone.

**Comment by HelOWeen** [comment] 2019-06-14 09:59
Although I initially deleted the plugins cache, when trying to resolve that issue by myself, and KeePass (re-)compiled the KeeAnywhere plugin on the next startup, it kept throwing the error I posted. What I didn't try: deleting the .json.

Will give that a try.

**Comment by Squale76** [comment] 2019-07-03 04:48
Hi Kyrodan,

Sorry for the late response.

My Framework is the 4.0.0.0 (see in \HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0\Client) and my Windows version is Windows 10 Entreprise.

Is it good to use your plugin ?

**Comment by HelOWeen** [comment] 2019-07-08 13:19
The suggestion of @ka5huk3n did the trick for me. Deleting both the compiled plugin itself and KeeAnywhere.Accounts.json got it working again. One needs to add the previously configured cloud provider(s) again.

**Comment by Helediron** [comment] 2019-07-09 19:30
Deleting the KeeAnywhere.Accounts.json file was enough for me. I got the error after copied a portable instance to another computer. So actually it was authentication issue and the "incompatible" error was just generic "oops" and misleading.

**Comment by Kyrodan** [comment] 2019-07-10 06:56
@Helediron you are right. I will implement a better message for the
unenecryption-error. That's currently leads to the many "Incompatible"
issues.

Am Di., 9. Juli 2019 um 21:30 Uhr schrieb Helediron <
notifications@github.com>:

**Comment by freMea** [comment] 2019-08-25 06:05
This issue can be closed as well as other related ones (#180 #169 #175) after notifying users that they need to delete those 3 items to reset the plugin after a Windows fresh install or copying keepass folder from one user to another one.
* [folder] PluginCache 
* [folder] KeeAnywhereOfflineCache
* [file] KeeAnywhere.Accounts.json

**Comment by Kyrodan** [comment] 2019-11-19 19:24
@freMea thanks for you Support here. I will improve the decryption of the tokens and improve the messages.

**Comment by Kyrodan** [comment] 2019-11-29 11:56
Duplicate of #169 - closing.

**Closed by Kyrodan** 2019-11-29 11:56 UTC
Labels: duplicate
