### ISSUE TITLE
Unhandled exception "No unused port found!"

### ISSUE THREAD

**Issue by alabamatoy** [Kyrodan/KeeAnywhere#347] opened 2022-07-07 10:55 UTC
Windows 7, Installed latest version of Keepass2, installed KeeAnywhere-2.0.3.plgx, opened Keepass, attempted to add GoogleDrive connection under keeanywhere settings, and got:
![image](https://user-images.githubusercontent.com/28680526/177757196-03f3d38b-e855-43cd-924a-7629a045511d.png)

```
************** Exception Text **************
System.Exception: No unused port found!
   at KeeAnywhere.OAuth2.OidcSystemBrowser..ctor(IEnumerable`1 ports)
   at KeeAnywhere.OAuth2.OidcFlow.<AuthorizeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.StorageProviders.GoogleDrive.GoogleDriveStorageConfigurator.<CreateAccount>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.StorageProviders.StorageService.<CreateAccount>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.UIService.<CreateOrUpdateAccount>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.SettingsForm.<OnAccountAdd>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.51.1.15884
    Win32 Version: 2.51.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.24.0.0
    Win32 Version: 1.24.0.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.51.1.15884
    Win32 Version: 2.51.1.15884
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.49.0.2201
    Win32 Version: 1.49.0.2201
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
IdentityModel.OidcClient
    Assembly Version: 3.0.0.0
    Win32 Version: 3.1.2.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/IdentityModel.OidcClient.DLL
----------------------------------------
IdentityModel
    Assembly Version: 4.1.0.0
    Win32 Version: 4.1.0.0
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/IdentityModel.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.18136
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Extensions.Logging.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.18136
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.18136
    CodeBase: file:///C:/Users/hre/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Extensions.Options.DLL
----------------------------------------
```

**Comment by Jackabomb** [comment] 2022-09-06 20:32
This looks like a duplicate of #301. Maybe the workaround in that thread will help you.

**Comment by alabamatoy** [comment] 2022-09-06 21:34
Looks like you are correct.  TYVM.

**Comment by Kyrodan** [comment] 2024-06-24 07:55
Duplicate to #301

**Closed by Kyrodan** 2024-06-24 07:55 UTC
