### ISSUE TITLE
Google Drive : subdirectory where are stored .kdbx files does not shown

### ISSUE THREAD

**Issue by accnetdev** [Kyrodan/KeeAnywhere#117] opened 2017-12-08 13:47 UTC
Hi,

On the newly installed keepass 2.36 or 2.37 with KeeAnywhere 1.4.1.0, I can access my Google Drive, a list of folders are shown but not the one where I store my .kdbx files.
The one is named ACCESS and it does not appears in KeeAnywhere.

If I access my Google Drive using Google Chrome browser (or from any other tool), I can see and use the directory ACCESS with all my .kdbx files.

What's wrong ?

**Comment by Kyrodan** [comment] 2017-12-08 14:53
Is it maybe from sync with your computer or a team folder? If yes, then issue #93 is relevant.

**Comment by Kyrodan** [comment] 2018-01-08 13:57
Duplicate of #93

**Closed by Kyrodan** 2018-01-08 13:57 UTC
Labels: duplicate
