### ISSUE TITLE
Incompatible with KeePass 2.38

### ISSUE THREAD

**Issue by laurentlbm** [Kyrodan/KeeAnywhere#120] opened 2018-01-24 14:30 UTC
When launching KeePass 2.38, this error is shown:
```
The following plugin is incompatible with the current KeePass version:
C:\Users\......\AppData\Local\KeePass\PluginCache\yCF3PAJRJXQzeCVhIILc\KeeAnywhere.dll

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
Key not valid for use in specified state.

System.Security
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at KeeAnywhere.Json.ProtectedDataStringPropertyResolver.ProtectedDataStringValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at KeeAnywhere.Configuration.ConfigurationService.LoadAccountsFromLocalSecureStore()
   at KeeAnywhere.Configuration.ConfigurationService.Load()
   at KeeAnywhere.KeeAnywhereExt.Initialize(IPluginHost pluginHost)
   at KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)
Byte[] Unprotect(Byte[], Byte[], System.Security.Cryptography.DataProtectionScope)
```

**Comment by rdolezel** [comment] 2018-01-25 13:14
The last working KeePass version for my KeeAnywhere-based Dropbox connection is 2.36. For 2.37 and 2.38  my trigger is never executed.

**Comment by Kyrodan** [comment] 2018-01-25 13:27
Duplicate of #95. KeeAnywhere is compatible with 2.37 and 2.38.

@rdolezel: what is your concrete issue? Please open another issue for that, if it differs from #95

**Closed by Kyrodan** 2018-01-25 13:27 UTC
Labels: duplicate
