### ISSUE TITLE
default folder did not create automatically

### ISSUE THREAD

**Issue by rosset** [Kyrodan/KeeAnywhere#96] opened 2017-07-21 19:46 UTC
First time I installed KeeAnywhere-1.4.1.plgx with KeePass 2.36 I had to create the following directory in my user folder "AppData\Local\KeePass\KeeAnywhereOfflineCache" otherwise the plugin crashes.

**Comment by Kyrodan** [comment] 2017-08-07 12:43
I could not reproduce this issue. Offline Cache Folder should always be created if tried to use it.

Did an Exception Message Box was shown? If yes: could you please restart KeePass using "-debug" and post the Exception Stack from the error message's temporary file here?

**Comment by Kyrodan** [comment] 2017-08-30 08:39
It should be created automatically but will throw an Exception if the folder could not be created anyway.

**Comment by Faark** [comment] 2018-02-23 13:10
I guess AppData\Local\KeePass\ may not exist in case the user does not use plgx files but instead dlls directly (easier for me to understand what code is running and debug it)

Here is a stack trace:

`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Faark\AppData\Local\KeePass\KeeAnywhere.Accounts.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at KeeAnywhere.Configuration.ConfigurationService.SaveAccountsToLocalSecureStore() in C:\Users\Faark\Source\Repos\KeeAnywhere\KeeAnywhere\Configuration\ConfigurationServiceLocalSecureStore.cs
   at KeeAnywhere.Configuration.ConfigurationService.Save() in C:\Users\Faark\Source\Repos\KeeAnywhere\KeeAnywhere\Configuration\ConfigurationService.cs
   at KeeAnywhere.Forms.SettingsForm.OnBtnOkClick(Object sender, EventArgs e) in C:\Users\Faark\Source\Repos\KeeAnywhere\KeeAnywhere\Forms\SettingsForm.cs
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by Kyrodan** [comment] 2018-09-20 14:12
Released in v1.5.0

**Closed by Kyrodan** 2018-09-20 14:12 UTC
Labels: bug
