### ISSUE TITLE
KeeAnywhere.dll v1.5.1 plugin incompatible with Keepass 2.41

### ISSUE THREAD

**Issue by whstrain** [Kyrodan/KeeAnywhere#169] opened 2019-03-25 17:38 UTC
I have the following error after upgrade: 
<img width="576" alt="Untitled" src="https://user-images.githubusercontent.com/19912589/54941776-07277280-4f04-11e9-9064-ab26833e8bb5.png">

**Comment by spawn-guy** [comment] 2019-03-26 11:44
@Kyrodan it is possible that i'm missing something on a fresh win10-x64 installation.
'cause i tried running this with KeePass 2.40 - and it still states that the plug-in is not compatible with the current version of KeePass.
i checked .net framework, but 4.7.2 doesn't want to install as i already have a newer version

![image](https://user-images.githubusercontent.com/1442562/54994549-cf343400-4fc4-11e9-8632-aebc839a3f4c.png)

**Comment by CommanderBond** [comment] 2019-03-27 15:32
Same here using KeePass 2.41 and KeeAnywhere 1.5.1 on Windows 10 after my Windows user was migrated to another domain. I got a new profile on my box because there went something wrong migrating my user, then ProfileDir in registry was redirected to point to the old profile directory.
I already purged the compiled cache folder (deleted KeeAnywhere.dll & Kyrodan.HiDrive) but I also get the key not valid error. Maybe something is encrypted with an old security identifier/key.

Some sites suggest to purge C:\Users\Username\AppData\Roaming\Microsoft\Crypto\RSA folder aas well, but moving the content out of the folder and then restarting KeePass to recompile the plugin did not help.

Does anybody know what has to be cleaned up to make KeeAnywhere work again?

**Comment by CommanderBond** [comment] 2019-04-01 13:04
> 
> 
> Same here using KeePass 2.41 and KeeAnywhere 1.5.1 on Windows 10 after my Windows user was migrated to another domain. I got a new profile on my box because there went something wrong migrating my user, then ProfileDir in registry was redirected to point to the old profile directory.
> I already purged the compiled cache folder (deleted KeeAnywhere.dll & Kyrodan.HiDrive) but I also get the key not valid error. Maybe something is encrypted with an old security identifier/key.
> 
> Some sites suggest to purge C:\Users\Username\AppData\Roaming\Microsoft\Crypto\RSA folder aas well, but moving the content out of the folder and then restarting KeePass to recompile the plugin did not help.
> 
> Does anybody know what has to be cleaned up to make KeeAnywhere work again?

My problem was caused by user ecrypted Local User Secure Store in %APPDATA%\KeePass\KeeAnywhere.Accounts.json as referenced here: 
https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#which-account-storage-location-should-i-choose

I uninstalled everything from KeyPass (executables, plugins, their caches and KeePass folders from profile directory (preserving the config file) and installed from scratch. Then I set up KeeAnywhere to connect to my DropBox and it worked again.

**Comment by spawn-guy** [comment] 2019-04-01 13:24
> My problem was caused by user ecrypted Local User Secure Store in %APPDATA%\KeePass\KeeAnywhere.Accounts.json as referenced here:
> https://github.com/Kyrodan/KeeAnywhere/wiki/Advanced-Topics#which-account-storage-location-should-i-choose
I, as well, changed my Windows profile settings (by Factory Resetting the laptop) and in my case KeePass is a Portable install -> the `KeeAnywhere.Accounts.json` file was in the folder with `.exe` file.
I deleted it, skipped the initial "login", then re-set up KeeAnywhere integration and it works again!

**Comment by whstrain** [comment] 2019-04-03 01:11
The bottom line is that something is caused the access token to go bad and either the application or the plugin is not failing nicely when GoogleDrive doesn't like the token. Either removing the .json file or removing the secret line from the file will allow the connection to the cloud storage to be setup again or reestablished. In the case of removing the secret line you should go into keeanywhere settings and click check.

**Comment by freMea** [comment] 2019-08-25 06:05
This issue can be closed as well as other related ones (#180 #169 #175) after notifying users that they need to delete those 3 items to reset the plugin after a Windows fresh install or copying keepass folder from one user to another one.
* [folder] PluginCache 
* [folder] KeeAnywhereOfflineCache
* [file] KeeAnywhere.Accounts.json

**Closed** 2019-11-29 13:06 UTC
Labels: bug
