### ISSUE TITLE
Database loading indefinitly in dropbox (KP 2.42.1)

### ISSUE THREAD

**Issue by sebigut** [Kyrodan/KeeAnywhere#178] opened 2019-05-28 10:53 UTC
When trying to load my database using dropbox it just stays trying to load forever. IF I load first a local database and then try to load the Dropbox one then it does opens. This behavior did not happen before using the last version of KP
![keepass](https://user-images.githubusercontent.com/14024884/58472905-b4de1a00-811d-11e9-924b-e266035f7d0e.jpg)

**Comment by opeeba** [comment] 2019-06-13 18:58
I have been experiencing this issue also.

**Comment by Kyrodan** [comment] 2020-01-09 13:52
I cannot reproduce this on KeePass 2.43 => closing.
If this ss this still reproducable by someone, then please reopen this issue.

**Closed by Kyrodan** 2020-01-09 13:52 UTC
