### ISSUE TITLE
google drive Authentication failed!

### ISSUE THREAD

**Issue by hiliangchunrui** [Kyrodan/KeeAnywhere#74] opened 2017-02-18 02:21 UTC
Authentication failed!

发送请求时出错。
Google.Apis.Core
   在 Google.Apis.Http.ConfigurableMessageHandler.<SendAsync>d__b.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.<ExecuteAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<FetchTokenAsync>d__1a.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<ExchangeCodeForTokenAsync>d__a.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 KeeAnywhere.StorageProviders.GoogleDrive.GoogleDriveStorageConfigurator.<Claim>d__c.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 KeeAnywhere.OAuth2.OAuth2Form.<OnNavigated>d__3.MoveNext()
Void MoveNext()

Inner:
无法连接到远程服务器
System
   在 System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   在 System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
System.IO.Stream EndGetRequestStream(System.IAsyncResult, System.Net.TransportContext ByRef)

**Comment by Kyrodan** [comment] 2017-02-20 09:10
Hi @hiliangchunrui 
is this a one-time failure or does it *always* fail?

**Comment by hiliangchunrui** [comment] 2017-02-20 14:15
@Kyrodan I think it's an always fail. I have never success.

**Comment by Kyrodan** [comment] 2017-04-18 13:23
Could you please describe, what exactly you are doing that lead to this error.

**Comment by tinuzz** [comment] 2017-04-26 09:05
I have the same problem, I think. This is the first time I try to use KeeAnywhere. I just downloaded the plugin from Github and installed in Keepass plugins folder.

First time I tried to add a Google account, Keepass crashed when clicking 'Next' after entering my user name. Second time, I was able to complete Google Authentication, but oAuth handling in KeeAnywhere seems off.

Add new account -> Google drive -> opens 'Authorize to Google Drive' window. Enter credentials and authentication with Google seems to work. Allow KeeAnywhere to access the Drive. So far everything looks good, but when the authentication window finally closes, Keepass / KeeAnywhere throws an error 'Authentication failed!' and the account is not added.

Tried a couple of times, fails every time, so I have not succeeded in accessing Google Drive from KeeAnywhere.

Anything I can do to help?

Cheers,
Martijn.

**Comment by Kyrodan** [comment] 2017-04-26 09:22
Hi @tinuzz,

Could you please try this Snapshot-Build: https://github.com/Kyrodan/KeeAnywhere/files/929813/KeeAnywhere-1.4.0-unstable.plgx.zip (rename file after downloading and remove extension ".zip" from it).

Please be aware, that this build may be unstable. Please just test your issue and report back.

**Comment by tinuzz** [comment] 2017-04-26 09:46
Hi Kyrondan,

I get the same error with v1.4.0 on Google Drive. Adding a OneDrive account works without problems.

Please let me know if there's anything else I can do.

Cheers,
Martijn.

**Comment by vsamukov** [comment] 2017-04-27 08:03
Hi Daniel,

First let me thank you for the great plugin you did here. Awesome job! 

And I seem to have this issue too. I have 2FA with my google account and whenever I try to connect KeeAnywhere, it throws error immediately I click "Allow" on the google authorization page after having entered the password and GoogleAuthenticator code. At the second attempt the plugin seemed the remember my account and password on Google, but clicking "Allow" will always throw "Authentication failed!" error. So far unable to connect google drive. 

---------------------------
KeePass - Fatal Error
---------------------------
A fatal error has occurred!

An extended error report has been copied to the clipboard.

Authentication failed!
---------------------------
OK   
---------------------------

*BTW nothing useful got into clipboard"

Let me know if I can do anything to help you to troubleshoot this.

**Comment by Kyrodan** [comment] 2017-04-27 08:31
Ok, thanks for all your feedback. I will take a look into it shortly.

**Comment by tinuzz** [comment] 2017-04-27 15:25
Oh yes, forgot to mention that I also have 2FA enabled with Google Authenticator.

Martijn.

**Comment by CumpsD** [comment] 2017-05-03 10:09
Same here, 2FA. Let me know if there is anything I can debug for you. First time I installed the plugin today

**Comment by erdy232** [comment] 2017-05-03 18:51
Having the same issue with Google Drive

**Comment by CumpsD** [comment] 2017-05-05 10:24
@Kyrodan it seems when finishing the Drive permissions browser, the problem is on this line:

`var isOk = await m_provider.Claim(e.Url, m_browser.DocumentTitle);`

```
public async Task<bool> Claim(Uri uri, string documentTitle)
        {
            var parts = documentTitle.Split(' ');

            if (parts.Length < 1 || parts[0] != "Success")
                return false;```

`m_browser.DocumentTitle` is now apparently an empty string, so it can't get a code out of it

**Comment by CumpsD** [comment] 2017-05-05 11:01
I've made a PR to get the code from the Uri, works on my machine ;)

**Comment by Kyrodan** [comment] 2017-05-08 10:22
Hi @CumpsD ,

thanks for your PR, hopefully I get it merged very soon.

**Comment by nilsrie** [comment] 2017-05-08 16:52
thank you! looking forward to the update :)

**Comment by olivdu67** [comment] 2017-05-12 12:06
Hi
Sorry for my english ... I'm french :)

I have the same problem when I try to add a google drive acount...
I choose local user secure store, add google drive ... I select my acount, (2 step verification) , and I authorize access... and crash  :(

What can I do ? 
Thank you

**Comment by Kyrodan** [comment] 2017-05-12 12:08
Hi @olivdu67 ,

you can only wait for a fix from me. Hope I get it out this weekend.
I'm sorry for your inconvenience.

**Comment by olivdu67** [comment] 2017-05-12 12:16
HI
For information, I tried with the KeeAnywhere-1.1.0.plgx... and it work good ! :)

**Comment by Bazz78** [comment] 2017-05-24 13:41
I confirm the issue

with 1.3.1 can't login to gmail 

With version 1.1.0 everything works

**Comment by Kyrodan** [comment] 2017-05-29 14:10
Hi all,

could you please try this unstable development build:
[KeeAnywhere-1.4.0-unstable.plgx.zip](https://github.com/Kyrodan/KeeAnywhere/files/1035989/KeeAnywhere-1.4.0-unstable.plgx.zip)

It already contains new features for the upcoming Version 1.4.0 - so this this is for testing only! 

Currently I'm polishing the new release, so your feedback is very welcome.

**Comment by vsamukov** [comment] 2017-05-29 14:26
Google 2FA works now!

**Comment by tinuzz** [comment] 2017-05-29 15:29
Can confirm that it works for me too with the 1.4.0 snapshot. Thanks!

**Closed** 2017-05-31 08:12 UTC
Labels: bug

**Comment by Kyrodan** [comment] 2017-06-01 11:37
@mbisanz @tinuzz @vsamukov ,

due to Bug #87 (which is similar to this) I had to rework Google Drive authentication again.
Could you please try this development snapshot and report back your (hopefully positive) results:
https://github.com/Kyrodan/KeeAnywhere/files/1044578/KeeAnywhere-1.4.1-unstable.plgx.zip

**Comment by tinuzz** [comment] 2017-06-01 12:25
I installed 1.4.1-unstable, removed the Google Drive account in KeeAnywhere and re-added it, requiring me to login again. I did all this while the Google-hosted database was open in KeePass. After re-adding the account I saved the database to Google Drive.

This all worked without probems.

Thank you!

**Comment by vsamukov** [comment] 2017-06-01 12:37
same at @tinuzz . 1.4.1 works!

**Comment by Kyrodan** [comment] 2017-06-01 12:46
Ok, great - thank you!

**Comment by mbisanz** [comment] 2017-06-02 06:46
Works for me with 1.4.1-unstable, too. Removed and re-added Google Drive account which triggered authentication (with 2FA).
